---
###  Run Settings Test File 
#
#### Declare paths and naming conventions:
user                         : 'Zach Waldron'
path_to_output_directory     : '/data/zach_work/output_from_runs'
directory_name_specifier     : ''  
PASS_INPUT_VALUE_TO_fortran  :  'None'

arc_length                   : '24hr'
model_data_path              :  None 

#### CD MODEL
cd_model  :   'BWDRAG' # 

file_string                  : 'bwdrag'
#### DRIA CD Model Parameters
cd_model_params : { 
#                     MS     : 26.0D0   ,  #!  molar mass for each panel (g/mol)
#                     TW     : 300.0D0  ,  #!  temperature of panels  (K)
#                     ALPHA  : 1.0D0    ,  #!  accomodation coefficient
#                     KL     : 0.0D0    ,  #!  langmuir parameter
#                     FRACOX : 0.90D0   ,  #!  fraction of surface covered by atomic oxygen
                   }

##### CHOOSE GEODYN VERSION:
GEODYN_iie_MOD_version     : 'CD_model_proj'
recompile_on               :  False

### IDENTIFY ARCS   (YYYY.DDD)
epoch_start         : [
#                     '181014 000000.0000000',
                    #
                    '181019 000000.0000000',
                    '181020 000000.0000000',
                    '181021 000000.0000000',
                    '181022 000000.0000000',
                    '181023 000000.0000000',
                    '181024 000000.0000000',
                    '181025 000000.0000000',
                    '181026 000000.0000000',                   
                    #
                    '181031 000000.0000000',                   
                    '181101 000000.0000000',                   
                    '181102 000000.0000000',                   
                    '181103 000000.0000000',                   
                    '181104 000000.0000000',                   
                    #
                    '181109 000000.0000000',
                    '181110 000000.0000000',
                    '181111 000000.0000000',
                    '181112 000000.0000000', 
                    '181113 000000.0000000',
                    '181114 000000.0000000',
                    '181115 000000.0000000',
                    '181116 000000.0000000',
                    '181117 000000.0000000',
                    '181118 000000.0000000',
                    '181119 000000.0000000',
                    '181120 000000.0000000',
                    '181121 000000.0000000',
                    '181122 000000.0000000',
                    '181123 000000.0000000',

                    #
                    '181201 000000.0000000',
                    '181202 000000.0000000',
                    '181203 000000.0000000',
                    #
                    '181215 000000.0000000',
                    '181216 000000.0000000',
                    '181217 000000.0000000',
                    '181218 000000.0000000',
                    #
                    '181222 000000.0000000',
                    '181223 000000.0000000',
                    '181224 000000.0000000',
                    #
                    '181231 000000.0000000',
                    '190101 000000.0000000',
                    '190102 000000.0000000',
                    '190103 000000.0000000',
                    '190104 000000.0000000',
                    '190105 000000.0000000',
                    '190106 000000.0000000',
                    '190107 000000.0000000',
                    '190108 000000.0000000',
                        ]
epoch_end           : [
#                     '181015 000000.0000000',
                    #
                    '181020 000000.0000000',
                    '181021 000000.0000000',
                    '181022 000000.0000000',
                    '181023 000000.0000000',
                    '181024 000000.0000000',
                    '181025 000000.0000000',
                    '181026 000000.0000000',
                    '181027 000000.0000000',                   
                    #
                    '181101 000000.0000000',                   
                    '181102 000000.0000000',                   
                    '181103 000000.0000000',                   
                    '181104 000000.0000000',                   
                    '181105 000000.0000000',                   
                    #
                    '181110 000000.0000000',
                    '181111 000000.0000000',
                    '181112 000000.0000000',
                    '181113 000000.0000000', 
                    '181114 000000.0000000',
                    '181115 000000.0000000',
                    '181116 000000.0000000',
                    '181117 000000.0000000',
                    '181118 000000.0000000',
                    '181119 000000.0000000',
                    '181120 000000.0000000',
                    '181121 000000.0000000',
                    '181122 000000.0000000',
                    '181123 000000.0000000',
                    '181124 000000.0000000',

                    #
                    '181202 000000.0000000',
                    '181203 000000.0000000',
                    '181204 000000.0000000',
                    #
                    '181216 000000.0000000',
                    '181217 000000.0000000',
                    '181218 000000.0000000',
                    '181219 000000.0000000',
                    #
                    '181223 000000.0000000',
                    '181224 000000.0000000',
                    '181225 000000.0000000',
                    #
                    '190101 000000.0000000',
                    '190102 000000.0000000',
                    '190103 000000.0000000',
                    '190104 000000.0000000',
                    '190105 000000.0000000',
                    '190106 000000.0000000',
                    '190107 000000.0000000',
                    '190108 000000.0000000',
                    '190109 000000.0000000',
                     ]
arc             : [ 
#                     '2018.287',
                    #
                    '2018.292',
                    '2018.293',
                    '2018.294',
                    '2018.295',
                    '2018.296',
                    '2018.297',
                    '2018.298',
                    '2018.299',                   
                    
                    '2018.304',
                    '2018.305',
                    '2018.306',
                    '2018.307',
                    '2018.308',
                    #
                    '2018.313',
                    '2018.314',
                    '2018.315',
                    '2018.316',
                    '2018.317',
                    '2018.318',
                    '2018.319',
                    '2018.320',
                    '2018.321',
                    '2018.322',
                    '2018.323',
                    '2018.324',
                    '2018.325',
                    '2018.326',
                    '2018.327',
                    #
                    '2018.335',
                    '2018.336',
                    '2018.337',
                    #
                    '2018.349',
                    '2018.350',
                    '2018.351',
                    '2018.352',
                    #
                    '2018.356',
                    '2018.357',
                    '2018.358',
                    #
                    '2018.365',
                    '2019.001',
                    '2019.002',
                    '2019.003',
                    '2019.004',
                    '2019.005',
                    '2019.006',
                    '2019.007',
                    '2019.008',
                    ]


satellite    : 'icesat2' 
den_model    : 'msis2'  
request_data :  ['Trajectory_orbfil',
                'Density',
                #'DragFile',
                'Residuals_summary', 
                #'RunSummary',
                # Residuals_obs',
                # 'AdjustedParams',
                                  ]
                                  
                                 
### SETUP FILE OPTIONS 
geodyn_StepSize           : 10.
cd_adjustment_boolean     : False
total_hours_in_run        : None
hours_between_cd_adj      : None
accels                    :  False
empirical_accels          :  False, 
ACCELS                    : 'acceloff'
cards_to_remove           : [ 'ACCEL9',
                              'ORBTVU',
                              'RESID',
                              'CON9PA',]
                  
#### USER AUXILLIARY OPTIONS
verbose         :  False
DRHODZ_update   :  True     #### Do you want to use the updated DRHODZ calculation? (recommended)



#### ----------------------------------------------------------------------------
#### Options that are hardcoded defaults for ICESAT2 class
#### ----------------------------------------------------------------------------
#### The name of the satellite
SATELLITE_dir  : 'icesat2'
#### Satellites COSPAR ID number
SATID          : '1807001'
#### Datatype being used as tracking data
DATA_TYPE      : 'PCE'
#### ----------------------------------------------------------------------------
####### File Choices:
#### G2B file name
g2b_file       : 'g2b_pce_fullset_nomaneuver'  
#### Atmospheric Gravity file name
atgrav_file    : 'ATGRAV.glo-3HR_20160101-PRESENT_9999_AOD1B_0006.0090'
#### Planetary Ephemeris file name
ephem_file     : 'ephem1430.data_2025'
#### Gravity field file name
gravfield_file : 'eigen-6c.gfc_20080101_do_200_fix.grv'
#### PCE Ascii textfile name
StateVector_epochs_datafile  : '/data/data_geodyn/inputs/icesat2/setups/PCE_ascii.txt'



