---

###  Run Settings Test File 


### RUN PARAMETERS
 run_params:
   'arc' : ['2018.316']
   'satellite' : 'icesat2' 
   'den_model' : 'msis2'  
   'SpecialRun_name' : '_valid_ctrlrun'  
   'verbose' : False
   'geodyn_StepSize' : float(10.)
   'action' : 'run'
   
   
### CARD CONTROL PARAMETERS




