site_name: Kamodo Analysis Suite

nav:
- Home: README.md
- About: about.md
- Introduction: notebooks/Kamodo.ipynb
- Visualization: notebooks/Visualization.ipynb
- Syntax: notebooks/Syntax.ipynb
- Kamodofying Models: notebooks/Kamodofying_Models.ipynb
- Field Integration: notebooks/FieldIntegration.ipynb
- Kameleon: notebooks/kameleon-kamodo.ipynb
- TIEGCM: notebooks/TIEGCM.ipynb
- CommandLine: notebooks/CommandLineInterface.ipynb
- Additional Resources: additional_resources.md

theme: readthedocs
plugins:
  - mknotebooks:
      execute: true
  - search
markdown_extensions:
  - admonition
  - tables
  - mdx_math:
      enable_dollar_delimiter: True 
  - toc:
      permalink: true
  - markdown_include.include:
      base_path: docs

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
